services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - roboshop

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    ports:
      - "8081:8081"
    networks:
      - roboshop

  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
    networks:
      - roboshop

networks:
  roboshop:
    driver: bridge

volumes:
  mongo-data:
